### ISSUE TITLE
Rewrite in Rust

### ISSUE THREAD

**Issue by matbme** [mirkobrombin/XMasGifts#3]

**Comment by mirkobrombin** [comment]
Hello Mat, thank you for your feedback.

I held a meeting with my team of elves, and after heated arguments, a few dismissals, and some insults (in the Christmas spirit), we concluded that rewriting XMasGifts in Rust might go against the Christmas spirit and make people unhappy.

Thanks again for your feedback, and I wish you happy holidays.
