### ISSUE TITLE
How to play

### ISSUE THREAD

**Issue by pietrodicaprio** [mirkobrombin/XMasGifts#5]
hello, i dont know how to play pls help me thank's

**Comment by mirkobrombin** [comment]
Hi Pietro, to play XMasGifts you need some tools:
- two hands, possibly paired
- a computer equipped with power supply, keyboard, mouse, monitor and audio speakers and possibly a subwoofer (the volume must be set to maximum)
- Vanilla OS as the operating system installed on the computer
- a cup of chocolate prepared by your town's Christmas elf
- a strictly Christmas blanket must have reindeer

Once you have satisfied the above requirements, you can click [this link](https://xmas.mirko.pm/), you will find yourself in front of a Christmas page with a Christmas menu with red Christmas buttons. Click the Christmas button that says "Instructions," then read the Christmas instructions, using the Christmas arrow buttons to browse through all the Christmas instructions. When you are sure you have learned the Christmas instructions, you can click the red Christmas button that says "Back" which will take you back to the previous Christmas menu, from where you can click the red Christmas button that says "Play", you will be taken to our purely Christmas game and you will have to put into practice what you have learned by reading the Christmas instructions.

I wish you a lot of fun playing our Christmas game.

**Comment by pietrodicaprio** [comment]
oh, i cant play, i don't have the first tool due complications

**Comment by mirkobrombin** [comment]
Sorry to hear this. You have 2 options:
- take them from someone else (check if it is allowed by the laws of your country)
- use your feet

**Comment by pietrodicaprio** [comment]
i see, im going to teach my dog how to play for me and ill post results

thank you!!111!11!1
